# Generated by Django 3.1.4 on 2020-12-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interest_collected', models.FloatField()),
                ('paid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('interest', models.FloatField()),
                ('cash_in_hand', models.IntegerField()),
                ('loan_given', models.IntegerField()),
                ('total_members', models.IntegerField()),
            ],
        ),
    ]
