# Generated by Django 3.1.4 on 2020-12-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interestshared',
            table='Interest-shared',
        ),
        migrations.AlterModelTable(
            name='monthinfo',
            table='Month-info',
        ),
    ]
