# Generated by Django 3.1.4 on 2020-12-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cd', models.IntegerField()),
                ('installment', models.IntegerField()),
                ('interest', models.FloatField()),
                ('total', models.FloatField()),
                ('loan_bal', models.FloatField()),
                ('month', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'complete',
            },
        ),
    ]
